---
title       : First Presentation with Slidify
subtitle    : Learning slidify
author      : QQ
job         : Stats
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F, results='hide'}
# make this an external chunk that can be included in any file
library(knitr)
```

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!
     + test1
     + test2

--- .class #id 

## Plot with rChart
```{r, echo = FALSE, results = 'hide'}
require(rCharts)
```
```{r echo = FALSE, results = 'asis'}
haireye = as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart',
  data = subset(haireye, Sex == 'Male')
)
n1$save('n1.html', standalone = TRUE)
cat('<iframe src="n1.html" width=100%, height=600></iframe>')
```

--- &radio

## Question 1

What is 1 + 1?

1. 1
2. _2_
3. 3
4. 4

*** .hint 
Use your brain!!

*** .explanation 
You are smart!
